package com.ecjtu.dao;

import com.ecjtu.entity.Clazz;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("clazzDao")
public interface ClazzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Fri Jun 08 08:20:51 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Fri Jun 08 08:20:51 CST 2018
     */
    int insert(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Fri Jun 08 08:20:51 CST 2018
     */
    int insertSelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Fri Jun 08 08:20:51 CST 2018
     */
    Clazz selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Fri Jun 08 08:20:51 CST 2018
     */
    int updateByPrimaryKeySelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Fri Jun 08 08:20:51 CST 2018
     */
    int updateByPrimaryKey(Clazz record);

    List<Clazz> selectStudentByClazz();
}